name: Nodejs CI/CD

on:
  push:
    branches: production
  pull_request:
    branches: production


jobs:
  build:
    name: new Ci build
    runs-on: ubuntu-latest
    
    steps:
      - name : checkout repo
        uses: actions/checkout@v4
      
      - name: use nodeks
        uses: actions/setup-node@v4
        with:
          node-version: '23.0.0'
        
      - name: install depedencies
        run: npm install
    

   
