name: Nodejs CI

on:
  push:
    branches: staging
  pull_request:
    branches: staging


jobs:
  build:
    name: new Ci build
    runs-on: ubuntu-latest
    
    steps:
      - name : checkout repo
        uses: actions/checkout@v4
      
      - name: use nodeks
        uses: actions/setup-node@v4
        with:
          node-version: '14'
        
      - name: install depedencies
        run: npm install

   
